# Generated by Django 4.2.5 on 2023-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.TextField()),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(blank=True, null=True)),
                ('avg_min_temp', models.FloatField(blank=True, null=True)),
                ('total_precipitation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.TextField()),
                ('date', models.DateField()),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
