# Generated by Django 4.2.5 on 2023-09-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='station_id',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('station_id', 'date')},
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('avg_max_temp', models.FloatField(blank=True, null=True)),
                ('avg_min_temp', models.FloatField(blank=True, null=True)),
                ('total_precipitation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('station_id', 'year')},
            },
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='station',
        ),
    ]
