# Generated by Django 4.2.5 on 2023-09-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_alter_weatherdata_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='weather_data',
        ),
    ]
