# Generated by Django 4.2.5 on 2023-09-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_alter_weatherdata_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'managed': False},
        ),
    ]
