# Generated by Django 4.2.5 on 2023-09-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0007_alter_weatherdata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualStatistics',
        ),
        migrations.AlterModelOptions(
            name='weatherstats',
            options={'managed': False},
        ),
    ]
