# Generated by Django 4.2.5 on 2023-09-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0008_delete_annualstatistics_alter_weatherstats_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherstats',
            table='weather_stats',
        ),
    ]
