# Generated by Django 4.2.5 on 2023-09-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weatherdata_station_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='weatherstats',
            old_name='station_id',
            new_name='station',
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('station', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weatherstats',
            unique_together={('station', 'year')},
        ),
    ]
