# Generated by Django 4.2.5 on 2023-09-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_rename_station_id_weatherdata_station_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
    ]
